sudo: false # to use faster container based build environment
language: elixir

elixir:
  - 1.6.6

otp_release:
  - 19.3
  - 20.3
  - 21.0

script:
  - mix credo
  - mix format --check-formatted
  - mix docs # generate docs to check if it is not breaking.
  - MIX_ENV=test mix coveralls.travis
