sudo: false # to use faster container based build environment
language: elixir

elixir:
  - 1.5.3
  - 1.6.0-rc.1

otp_release:
  - 19.3
  - 20.2

after_script:
  - MIX_ENV=dev mix credo
  - mix deps.get --only docs
  - MIX_ENV=docs mix docs # generate docs to check if it is not breaking.
  - MIX_ENV=test mix bench
  - MIX_ENV=test mix coveralls.travis
